### ISSUE TITLE
QQ复读机+1符号歪了

### ISSUE THREAD

**Issue by lucayunxiao** [ferredoxin/QNotified#224]
QQ版本8.4.5.4745，Edxp版本canary YAHFA-0.5.05. +1符号歪了，整体靠下。
![Snipaste_2020-08-23_17-19-37](https://user-images.githubusercontent.com/34306081/90973379-d5856180-e564-11ea-8be0-52f7793cf316.png)

**Comment by hehua04** [comment]
> 这个+1是QQ自己的+1，QQ自己的+1本来有时就会玄学偏下的，我也没有办法

似乎并不是自己的，私聊里就有这问题，群里没有

**Comment by username-long111** [comment]
复读机问题找bug去

________________
2855669787@qq.com




---原始邮件---
发件人: &quot;hehua04&quot;<notifications@github.com&gt;
发送时间: 2020年11月15日(周日) 晚上6:45
收件人: &quot;ferredoxin/QNotified&quot;<QNotified@noreply.github.com&gt;;
抄送: &quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题: Re: [ferredoxin/QNotified] QQ复读机+1符号歪了 (#224)




  
这个+1是QQ自己的+1，QQ自己的+1本来有时就会玄学偏下的，我也没有办法
  
似乎并不是自己的，私聊里就有这问题，群里没有
 
&mdash;

**Comment by hehua04** [comment]
不，这指的是QN里的复读机功能（即+1功能）

Best regards,
Zou Yida
________________________________
发件人: username-long111 <notifications@github.com>
发送时间: 2020年11月15日 18:58
收件人: ferredoxin/QNotified <QNotified@noreply.github.com>
抄送: hehua04 <zouyida04@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [ferredoxin/QNotified] QQ复读机+1符号歪了 (#224)


复读机问题找bug去

________________
2855669787@qq.com




---原始邮件---
发件人: &quot;hehua04&quot;<notifications@github.com&gt;
发送时间: 2020年11月15日(周日) 晚上6:45
收件人: &quot;ferredoxin/QNotified&quot;<QNotified@noreply.github.com&gt;;
抄送: &quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题: Re: [ferredoxin/QNotified] QQ复读机+1符号歪了 (#224)





这个+1是QQ自己的+1，QQ自己的+1本来有时就会玄学偏下的，我也没有办法

似乎并不是自己的，私聊里就有这问题，群里没有

&mdash;
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

―

**Comment by taycke** [comment]
@hehua04 那个＋1我们是直接拉的QQ自己的＋1，因为QQ私聊自身没有＋1这个玩意所以就可能玄学了

**Comment by username-long111** [comment]
问马化腾去

________________
2855669787@qq.com




---原始邮件---
发件人: &quot;taycke&quot;<notifications@github.com&gt;
发送时间: 2020年11月15日(周日) 晚上9:46
收件人: &quot;ferredoxin/QNotified&quot;<QNotified@noreply.github.com&gt;;
抄送: &quot;username-long111&quot;<2855669787@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题: Re: [ferredoxin/QNotified] QQ复读机+1符号歪了 (#224)




 
@hehua04 那个＋1我们是直接拉的QQ自己的＋1，因为QQ私聊自身没有＋1这个玩意所以就可能玄学了
 
&mdash;

**Comment by hehua04** [comment]
OK知道了

Best regards,
Zou Yida
________________________________
发件人: taycke <notifications@github.com>
发送时间: 2020年11月15日 21:46
收件人: ferredoxin/QNotified <QNotified@noreply.github.com>
抄送: hehua04 <zouyida04@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [ferredoxin/QNotified] QQ复读机+1符号歪了 (#224)


@hehua04<https://github.com/hehua04> 那个＋1我们是直接拉的QQ自己的＋1，因为QQ私聊自身没有＋1这个玩意所以就可能玄学了

―
