### ISSUE TITLE
[QQ 8.5.5] Bug 收集

### ISSUE THREAD

**Issue by NextAlone** [ferredoxin/QNotified#436]
请简述无法使用的功能

**Comment by lyc13822711** [comment]
简洁模式圆头像初始化失败
新版简洁模式圆头像初始化失败
强制使用系统相机初始化失败

**Comment by ketal178** [comment]
VasProfileAntiCrash.java
https://paste.ubuntu.com/p/d9TtqqqJwJ/

**Comment by AoaoMH** [comment]
花Q里的免广告送免费礼物无效
QQ版本8.5.5 QN版本0.8.10.260

**Comment by NextAlone** [comment]
> 花Q里的免广告送免费礼物无效
> QQ版本8.5.5 QN版本0.8.10.260

热更新导致，等待下版本修复，热更新提不出来

**Comment by NextAlone** [comment]
> 简洁模式圆头像初始化失败
> 新版简洁模式圆头像初始化失败
> 强制使用系统相机初始化失败

简洁模式已启用，新版简洁模式已适配

**Comment by AoaoMH** [comment]
> > 花Q里的免广告送免费礼物无效
> > QQ版本8.5.5 QN版本0.8.10.260
> 
> 热更新导致，等待下版本修复，热更新提不出来

那是否在QN里设置防止热更新后，重新安装QQ可以解决该问题？

**Comment by ketal178** [comment]
@AoaoMH 可以一试

**Comment by NextAlone** [comment]
@AoaoMH 理论上是这样 但是不确保防止热更新还能不能用

**Comment by tomorrow8604** [comment]
用一段时间就闪退，点QQ钱包、链接也闪退

**Comment by NextAlone** [comment]
@tomorrow8604 能够提供一下崩溃时的调用栈吗

**Comment by tomorrow8604** [comment]
@NextAlone 那个我不知道怎么调

**Comment by NextAlone** [comment]
@tomorrow8604 看一下logcat的使用方法，然后在崩溃时提取一下

**Comment by tomorrow8604** [comment]
@NextAlone 是bate里面的那个logcat吗

**Comment by NextAlone** [comment]
@tomorrow8604 https://developer.android.com/studio/command-line/logcat?hl=zh-cn       adb logcat那个

**Comment by NextAlone** [comment]
@tomorrow8604 去酷安下一个matlog也可以4

**Comment by tomorrow8604** [comment]
@NextAlone 好的👌

**Comment by tomorrow8604** [comment]
@NextAlone 我用matlog显示一直加载

**Comment by qwq233** [comment]
@tomorrow8604 下载Android的sdk工具

**Comment by tomorrow8604** [comment]
@NextAlone 然后用adb试了一下不知道对了没

**Comment by qwq233** [comment]
@tomorrow8604 打开开发者模式
cmd(或者powershell随便你)
adb logcat

**Comment by tomorrow8604** [comment]
@NextAlone 
这个抓的不知道是不是https://paste.ubuntu.com/p/Yxm8CRc3DT/

**Comment by ketal178** [comment]
@tomorrow8604 你抓了个寂寞，过滤一下TAG

**Comment by NextAlone** [comment]
@tomorrow8604 关掉beta里的qq日志

**Comment by NextAlone** [comment]
@tomorrow8604 里面应该含有exception或者fatal之类的

**Comment by tomorrow8604** [comment]
@NextAlone 我好像没开日志

**Comment by tomorrow8604** [comment]
我用matlog抓了一下，然后QQ又好了……QQ钱包和链接跳转不闪退了
这个是刚刚matlog抓的https://paste.ubuntu.com/p/6DrHQyvDYX/

**Comment by ketal178** [comment]
@tomorrow8604 有些东西确实第一次打开会闪退，第2次就好了，怀疑是hook框架的问题
并不是模块的问题

**Comment by tomorrow8604** [comment]
@ketal178 我也不知道用matlog抓之前都闪退抓了后就好了莫名其妙的hhh

**Comment by tomorrow8604** [comment]
我就是升级了一下QQ和模块今天才出现闪退之前也是好好的

**Comment by tomorrow8604** [comment]
@NextAlone 大佬帮忙看一下还是闪退我点了网易云跳转链接（什么跳转链接都不行）和qq钱包

https://paste.ubuntu.com/p/HwPWRXyS7V/

**Comment by Neturalized** [comment]
新版简洁模式圆头像仍旧无法使用
2021.2.9

**Comment by qwq233** [comment]
@Neturalized 未测试出有该情况 有可能是你自己的问题

**Comment by Neturalized** [comment]
> @Neturalized 未测试出有该情况 有可能是你自己的问题

或许是因为我用的太极吧

**Comment by bybl6966** [comment]
貌似..消息检查功能早已失效？

**Comment by NextAlone** [comment]
@bybl6966 是

**Comment by bybl6966** [comment]
> @ bybl6966是

蛮实用的功能，不打算再更嘛

**Comment by ketal178** [comment]
> 貌似..消息检查功能早已失效？

还能用，前提是别开简洁模式

**Comment by bybl6966** [comment]
> > 貌似..消息检查功能早已失效？
> 
> 还能用，前提是别开简洁模式

确实能看到消息的dump，但是撤回的话只能撤回自己的消息。

**Comment by NextAlone** [comment]
@bybl6966 自己的也无法撤回，效果与删除相同

**Comment by ketal178** [comment]
> > > 貌似..消息检查功能早已失效？
> > 
> > 
> > 还能用，前提是别开简洁模式
> 
> 确实能看到消息的dump，但是撤回的话只能撤回自己的消息。

只能撤回你 有权限撤回的消息，之前的私聊撤回对方消息是tx的bug，现在腾讯修复了
撤回不了

**Comment by ellieot** [comment]
更新之后设置入口消失

**Comment by ketal178** [comment]
@ellieot 有没有考虑过是太极的问题

**Comment by Neturalized** [comment]
> 更新之后设置入口消失

请更新太极内核或下载最新版太极

**Comment by ellieot** [comment]
> > 更新之后设置入口消失
> 
> 请更新太极内核或下载最新版太极

使用edxposed版本4.6.2，面具版本20400

`
02-15 15:00:56.512 18023 18023 I EdXposed-Bridge: [ExLink] 进入QQ(com.tencent.mobileqq)
02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.tencent.mobileqq/files/qn_dyn_lib/libnatives_arm64-v8a_0.8.10.260.badce21.so" is 64-bit instead of 32-bit
02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: 	at java.lang.Runtime.load0(Runtime.java:938)
02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: 	at java.lang.System.load(System.java:1631)
02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: 	at nil.nadph.qnotified.util.Natives.load(Natives.java:23)
02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: 	at nil.nadph.qnotified.StartupHook$1.afterHookedMethod(StartupHook.java:12)
02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: 	at EdHooker_633f457500df0ac50505321302fff4008eb8fb3f.hook(Unknown Source:132)
02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: 	at com.tencent.mobileqq.startup.step.Step.step(P:126)
02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: 	at com.tencent.mobileqq.startup.step.Step.doStep(P:158)
02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: 	at com.tencent.mobileqq.startup.step.Step.step(P:126)
02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: 	at com.tencent.mobileqq.startup.director.StartupDirector.a(P:401)
02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: 	at com.tencent.common.app.BaseApplicationImpl.onCreate(P:335)
02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: 	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(P:30)
02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6609)
02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: 	at EdHooker_42b8453bf7df105343083f1377c32094be493c49.hook(Unknown Source:120)
02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: 	at android.app.ActivityThread.access$1400(ActivityThread.java:229)
02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1892)
02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:107)
02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:228)
02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:7589)
02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
`

**Comment by Neturalized** [comment]
> > > 更新之后设置入口消失
> > 
> > 
> > 请更新太极内核或下载最新版太极
> 
> 使用edxposed版本4.6.2，面具版本20400
> 
> `02-15 15:00:56.512 18023 18023 I EdXposed-Bridge: [ExLink] 进入QQ(com.tencent.mobileqq) 02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.tencent.mobileqq/files/qn_dyn_lib/libnatives_arm64-v8a_0.8.10.260.badce21.so" is 64-bit instead of 32-bit 02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: at java.lang.Runtime.load0(Runtime.java:938) 02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: at java.lang.System.load(System.java:1631) 02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: at nil.nadph.qnotified.util.Natives.load(Natives.java:23) 02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: at nil.nadph.qnotified.StartupHook$1.afterHookedMethod(StartupHook.java:12) 02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68) 02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: at EdHooker_633f457500df0ac50505321302fff4008eb8fb3f.hook(Unknown Source:132) 02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: at com.tencent.mobileqq.startup.step.Step.step(P:126) 02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: at com.tencent.mobileqq.startup.step.Step.doStep(P:158) 02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: at com.tencent.mobileqq.startup.step.Step.step(P:126) 02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: at com.tencent.mobileqq.startup.director.StartupDirector.a(P:401) 02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: at com.tencent.common.app.BaseApplicationImpl.onCreate(P:335) 02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: at com.tencent.mobileqq.qfix.QFixApplication.onCreate(P:30) 02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190) 02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6609) 02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: at EdHooker_42b8453bf7df105343083f1377c32094be493c49.hook(Unknown Source:120) 02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: at android.app.ActivityThread.access$1400(ActivityThread.java:229) 02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1892) 02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: at android.os.Handler.dispatchMessage(Handler.java:107) 02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: at android.os.Looper.loop(Looper.java:228) 02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: at android.app.ActivityThread.main(ActivityThread.java:7589) 02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: at java.lang.reflect.Method.invoke(Native Method) 02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 02-15 15:00:57.080 18023 18023 E EdXposed-Bridge: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)`

用的面具啊，那就没我什么事

**Comment by CirnoSalt** [comment]
QQ ：8.5.5 
QN：0.8.11
太极：6.1.2
旧版简洁模式圆头像初始化失败
新版圆头像开启后头像一直闪烁无法加载
![Screenshot_20210217125900](https://user-images.githubusercontent.com/23478997/108158472-f39cda80-711f-11eb-8dbc-b83e7cd9a789.jpg)
清除QQ/模块数据无法解决。

**Comment by singleNeuron** [comment]
@CirnoSalt 闪烁的时候一直放在那个页面等着，可能需要几分钟的时间刷新缓存

**Comment by CirnoSalt** [comment]
等待了10分钟后问题依旧，主页头像还是方形并且一直闪烁，聊天界面内头像无法加载。

**Comment by Neturalized** [comment]
> 等待了10分钟后问题依旧，主页头像还是方形并且一直闪烁，聊天界面内头像无法加载。

同问题，之前回答说是设备问题

**Comment by singleNeuron** [comment]
@Neturalized 请报告QQ版本和QN版本

**Comment by Neturalized** [comment]
> @Neturalized 请报告QQ版本和QN版本

QN版本是0.8.11.265.d3ba0e0（最新版本太极尚不支持）QQ是8.5.5

**Comment by qwq233** [comment]
此issue封存，请单开issue
